# Generated by Django 5.0 on 2026-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
