# Generated by Django 5.0 on 2026-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
