# Generated by Django 5.0 on 2026-03-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.AddField(
            model_name='item',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
