# Generated by Django 5.0 on 2026-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='numorders',
            field=models.IntegerField(db_default=models.Value(0)),
        ),
        migrations.AddField(
            model_name='movie',
            name='numreviews',
            field=models.IntegerField(db_default=models.Value(0)),
        ),
    ]
