# Generated by Django 5.0 on 2026-03-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_numorders_movie_numreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mostorders',
            field=models.CharField(db_default=models.Value('No'), max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='mostreviews',
            field=models.CharField(db_default=models.Value('No'), max_length=3),
        ),
    ]
