# Generated by Django 5.0 on 2026-03-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_mostorders_movie_mostreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mostorders',
            field=models.CharField(db_default=models.Value('No'), max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mostreviews',
            field=models.CharField(db_default=models.Value('No'), max_length=10),
        ),
    ]
