# Generated by Django 5.0 on 2026-03-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Commenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numComments', models.IntegerField(db_default=models.Value(0))),
                ('mostComments', models.BooleanField(db_default=models.Value(False))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
